services: [
  {
    groupId: ${artifact.groupId},
    artifactId: ${artifact.artifactId},
    version: ${artifact.version},
    runsInContainer: 0,
    testOnDeploy: <#if artifact.testOnDeploy>1<#else>0</#if>
  }
]
